services:
  nextcloud-app:
    image: nextcloud:28-fpm
    container_name: nextcloud-app
    restart: unless-stopped
    ports:
      - "${NEXTCLOUD_PORT}:80"
    volumes:
      - nextcloud_data:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${NEXTCLOUD_DB_NAME}
      - MYSQL_USER=${NEXTCLOUD_DB_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASS}
      - REDIS_HOST=redis
    depends_on:
      - db
      - redis

  db:
    image: mariadb:11
    container_name: nextcloud-db
    restart: unless-stopped
    volumes:
      - nextcloud_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_ROOT_PASS}
      - MYSQL_DATABASE=${NEXTCLOUD_DB_NAME}
      - MYSQL_USER=${NEXTCLOUD_DB_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASS}

  redis:
    image: redis:7-alpine
    container_name: nextcloud-redis
    restart: unless-stopped

volumes:
  nextcloud_data:
  nextcloud_db_data:

